spring:
  application:
    name: character-app
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: admin
    password: revature

  h2:
    console:
      path: /h2
      settings:
        web-allow-others: true
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 5000